/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#d061ff",
        "surface-container-low": "#131314",
        "secondary": "#00eefc",
        "on-surface-variant": "#adaaab",
        "on-secondary-container": "#e3fdff",
        "primary-dim": "#bb00fc",
        "primary-fixed": "#d878ff",
        "on-surface": "#ffffff",
        "primary": "#df8eff",
        "error": "#ff6e84",
        "on-error": "#490013",
        "secondary-fixed-dim": "#00deec",
        "tertiary": "#ac89ff",
        "surface-container-high": "#201f21",
        "inverse-surface": "#fcf8f9",
        "background": "#0e0e0f",
        "surface-container-highest": "#262627",
        "surface-tint": "#df8eff",
        "on-tertiary-fixed-variant": "#4700a7",
        "on-primary-fixed-variant": "#4b0068",
        "on-secondary-fixed-variant": "#005e64",
        "secondary-container": "#006970",
        "inverse-on-surface": "#565556",
        "outline-variant": "#484849",
        "surface-dim": "#0e0e0f",
        "surface-variant": "#262627",
        "tertiary-fixed-dim": "#b190ff",
        "on-background": "#ffffff",
        "on-primary": "#4f006d",
        "surface-bright": "#2c2c2d",
        "on-tertiary-container": "#f8f1ff",
        "error-container": "#a70138",
        "secondary-dim": "#00deec",
        "primary-container": "#d878ff",
        "on-primary-container": "#3d0055",
        "on-secondary-fixed": "#003f43",
        "surface": "#0e0e0f",
        "secondary-fixed": "#00eefc",
        "on-secondary": "#005359",
        "error-dim": "#d73357",
        "on-primary-fixed": "#000000",
        "inverse-primary": "#9a00d0",
        "on-tertiary-fixed": "#1f0052",
        "on-error-container": "#ffb2b9",
        "tertiary-container": "#7000ff",
        "outline": "#767576",
        "surface-container": "#1a191b",
        "tertiary-dim": "#874cff",
        "tertiary-fixed": "#bda1ff",
        "on-tertiary": "#290067",
        "surface-container-lowest": "#000000",
        // Keeping agent specific colors for Canvas dashboard
        agent: {
          cyan: '#8ff5ff',
          violet: '#df8eff',
          emerald: '#4ade80',
          amber: '#fbbf24',
          rose: '#fb7185',
        },
      },
      fontFamily: {
        headline: ['Lexend', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
